spring:
  application:
    name: moviebookingapp

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: ${MOVIE_BOOKING_APP_DB_URL:jdbc:mysql://localhost:3307/moviebookingapp}
    username: ${MOVIE_BOOKING_APP_DB_USER:moviebooking}
    password: ${MOVIE_BOOKING_APP_DB_PASSWORD:moviebooking}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true